//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_1718_presences_g13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public int Student { get; set; }
        public int CourseOccurence { get; set; }
        public short Present { get; set; }
    
        public virtual CourseOccurrence CourseOccurrence { get; set; }
        public virtual Student Students { get; set; }
    }
}
